name: Android CI/CD
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'develop'
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Init gradle wrapper
        run: gradle wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Init gradle wrapper
        run: gradle wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build staging APK
        run: bash ./gradlew assembleStaging --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/staging/app-staging.apk
  build:
    name: Upload APK to App Testers
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Init gradle wrapper
        run: gradle wrapper
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: build staging
        run: bash ./gradlew assembleStaging
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: all-testers
          file: app/build/outputs/apk/staging/app-staging.apk