name: Android CI/CD

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [staging, release]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project
      - name: Build with Gradle
        run: ./gradlew clean bundle${{ matrix.variant }} -PversionCode=$VERSION_CODE -PversionName=$VERSION_NAME

      # Generate release notes from Git commits
      - name: Generate Release Notes from Git
        id: release_notes
        run: |
          echo "Collecting commits for release notes"
          git log $(git describe --tags --abbrev=0)..HEAD --oneline > release_notes.txt
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      # Deploy to Google Play Internal Testing for staging branch
      - name: Deploy to Google Play (Internal Testing)
        if: github.ref == 'refs/heads/staging'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_KEY }}
          packageName: ${{ secrets.PACKAGE_NAME }}
          releaseFiles: app/build/outputs/bundle/staging/app-staging.aab
          track: internal
          userFraction: 0.99
          inAppUpdatePriority: 0
          status: completed
          changesNotSentForReview: false

      # Deploy to Google Play Production for main branch
      - name: Deploy to Google Play (Production)
        if: github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_KEY }}
          packageName: ${{ secrets.PACKAGE_NAME }}
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          userFraction: 0.99
          inAppUpdatePriority: 0
          status: completed
          changesNotSentForReview: false