name: Android CI/CD

on:
  push:
    branches:
      - staging
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [staging, release]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      # Cache Gradle dependencies
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Decode and write the keystore file from the base64 secret
      - name: Decode and write the keystore file
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ github.workspace }}/splicr-keystore.jks

      # Build the project
      - name: Build with Gradle
        run: ./gradlew clean bundle${{ matrix.variant }} -PversionCode=$VERSION_CODE -PversionName=$VERSION_NAME
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_PATH: ${{ github.workspace }}/splicr-keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      # Sign the AAB with jarsigner
      - name: Sign the AAB with jarsigner
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore ${{ github.workspace }}/splicr-keystore.jks \
            -storepass ${{ secrets.KEYSTORE_PASSWORD }} \
            -keypass ${{ secrets.KEY_PASSWORD }} \
            app/build/outputs/bundle/${{ matrix.variant }}/app-${{ matrix.variant }}.aab \
            ${{ secrets.KEY_ALIAS }}

      # Generate release notes from the triggering commit
      - name: Generate Release Notes from Commit
        id: release_notes
        run: |
          echo "Generating release notes from the triggering commit"
          echo "${{ github.event.head_commit.message }}" > release_notes.txt

      # Save release notes to a directory for use in deployment
      - name: Save Release Notes
        run: |
          mkdir -p release-notes
          mv release_notes.txt release-notes/${{ matrix.variant }}-whatsnew.txt

      # Deploy to Google Play Internal Testing for staging branch
      - name: Deploy to Google Play (Internal Testing)
        if: github.ref == 'refs/heads/staging'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_KEY }}
          packageName: ${{ secrets.PACKAGE_NAME_INTERNAL }}
          releaseFiles: app/build/outputs/bundle/staging/app-staging.aab
          whatsNewDirectory: release-notes
          track: internal
          status: draft

      # Deploy to Google Play Production for main branch
      - name: Deploy to Google Play (Production)
        if: github.ref == 'refs/heads/main'
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_API_KEY }}
          packageName: ${{ secrets.PACKAGE_NAME_PRODUCTION }}
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          whatsNewDirectory: release-notes
          inAppUpdatePriority: 5